version: 1.0.{build}

image: Visual Studio 2019

# environment variables
environment:
  webApiProject: NetCore.WebApi/NetCore.WebApi.csproj
  webApiProjecTest: NetCore.WebApi.Test/NetCore.WebApi.Test.csproj
  xamarinAppProject: Xamarin.Droid/Xamarin.Droid.csproj
  xamarinAppProjectTest: Xamarin.Droid.Test/Xamarin.Droid.Test.csproj
  token:
    secure: R/Ib9FseHc+V708pLGYCJ+MqRXVrPcYDnrz+u/O94GLt5YWvNEpkf28Z3bDrHRLm

init:
  - cmd: dotnet tool install -g dotnet-sonarscanner
  - cmd: dotnet tool install -g coverlet.console
  - cmd: nuget install Appveyor.TestLogger -Version 2.0.0

install:
before_build:
  - cmd: dotnet --version
  - cmd: nuget restore
  
build_script:
  - cmd: dotnet-sonarscanner begin /k:"zanuccod_XamarinApp.NetCoreWebApi.TravisBuild" /o:"zanuccod" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=%token%
  - cmd: dotnet build %webApiProject%
  - cmd: msbuild "%xamarinAppProject%"

test_script:
  - cmd: dotnet test %webApiProjecTest% /p:CollectCoverage=true /p:CoverletOutputFormat=json /p:CoverletOutput=../../TestResults/TestResult.json
  - cmd: dotnet test %xamarinAppProjectTest% /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../../TestResults/TestResult.xml /p:MergeWith=../../TestResults/TestResult.json

on_finish:
  - cmd: dotnet-sonarscanner end /d:sonar.login=%token%
  
deploy: off